#+TITLE: Personal Emacs configuration
#+AUTHOR: jurdanetac
#+STARTUP: content

* Load these settings on your init.el!
  Using Org mode to tweak Emacs is a great way to organize and highlight parts
  of your custom configuration. Remember to load this org file in your init.el!

#+BEGIN_SRC
(org-babel-load-file
 (expand-file-name "settings.org"
                   user-emacs-directory))
#+END_SRC

* Add-ons
** Sources
   MELPA is an ELPA-compatible package repository that contains an enormous
   amount of useful Emacs packages. In contrast to ELPA, Emacs is not configured
   by default to install packages from MELPA. You will have to configure it.

#+BEGIN_SRC emacs-lisp
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)

;; Update package archives if no past data is found
(unless package-archive-contents
  (package-refresh-contents))
#+END_SRC

** Theme
   An opinionated pack of modern color-themes, a fancy and fast mode-line
   inspired by minimalism design and pretty icons. (Doom Emacs theme)

#+BEGIN_SRC emacs-lisp
(use-package doom-themes
  :init (load-theme 'doom-one t))

(use-package doom-modeline
  :init (doom-modeline-mode 1))

(use-package all-the-icons)
#+END_SRC

** Packages

#+BEGIN_SRC emacs-lisp
;; Use-package declaration for simplifying your .emacs
(unless (package-installed-p 'use-package)
  (package-install 'use-package))

;; Ensure all packages are installed on launch
(setq use-package-always-ensure t)

;; Vi emulation layer
(use-package evil
  :init (evil-mode 1))
#+END_SRC

* UI Tweaks
** Lines and characters

#+BEGIN_SRC emacs-lisp
;; Display line numbers and truncate long lines
(global-display-line-numbers-mode 1)
(global-visual-line-mode t)

;; Display matching pairs of ()[]{} without delay
(setq show-paren-delay 0)
(show-paren-mode 1)
#+END_SRC

** Disable stuff

#+BEGIN_SRC emacs-lisp
;; Hide interface tools
(setq inhibit-startup-screen t)
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)

;; Disable all alarms, sound is annoying and visual bell hangs the screen for a
;; while when top/bottom is reached with mouse scrolling
(setq ring-bell-function 'ignore)
#+END_SRC

* Keybindings
  These are user-defined shorcuts for functions, re-binding, etc...
  Vi-like layer is covered by Evil mode on Packages!

** Shortcuts for +/- zooming

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-=") 'text-scale-increase)
(global-set-key (kbd "C--") 'text-scale-decrease)
#+END_SRC

* Mouse scrolling
  Tweaks to move around the buffer more neatly with the mouse's wheel

#+BEGIN_SRC emacs-lisp
;; >100 gets rid of half page jumping
(setq scroll-conservatively 101)
;; Accelerate scrolling
(setq mouse-wheel-progressive-speed 1)
;; Lines at a time
(setq mouse-wheel-scroll-amount '(3 ((shift) . 3)))
#+END_SRC

* Whitespace
  I like the MSWord-like approach of the pilcrow (¶) toggle formatting marks

#+BEGIN_SRC emacs-lisp
;; Use spaces instead of tabs
(setq-default indent-tabs-mode nil)

;; Highlight whitespace and after-80 columns
(setq whitespace-style '(face trailing space-mark tab-mark lines-tail))
(global-whitespace-mode t)

;; Delete trailing whitespace on save
(add-hook 'before-save-hook
          (lambda ()
            (unless (eq major-mode 'fundamental-mode)
              (delete-trailing-whitespace))))
#+END_SRC

* Dashboard
  An extensible emacs startup screen showing you what’s most important.

#+BEGIN_SRC emacs-lisp
(use-package dashboard
  :init
  (setq dashboard-center-content t)
  (setq dashboard-set-file-icons t)
  (setq dashboard-startup-banner "~/.emacs.d/banners/oldlogo.png")
  (setq dashboard-banner-logo-title "An extensible, customizable, free/libre text editor — and more!")
  :config
  (dashboard-setup-startup-hook))
#+END_SRC
