# Display directories as trees (with optional color/HTML output)
brew "tree"
# Automate deployment, configuration, and upgrading
brew "ansible"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Modern, maintained replacement for ls
brew "eza"
# Interactive computing in Python
brew "ipython"
# Media player based on MPlayer and mplayer2
brew "mpv"
# Drop-in replacement for Terraform. Infrastructure as Code Tool
brew "opentofu"
# Ruby version manager
brew "rbenv"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Sends magic packets to wake up network-devices
brew "wakeonlan"
# Extensible command-line tool to format YAML files
brew "yamlfmt"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# System monitor for the menu bar
cask "stats"
# Open-source BitTorrent client
cask "transmission"
